eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/
server:
  port: 9000
spring:
  application:
    name: service-feign
  jackson:
    serialization.indent_output: true
feign:
  hystrix:
    enabled: true
  httpclient:
    enabled:  true